package com.vista2;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HikingCarrot7
 */
public class MenuTienda extends JDialog
{

    public MenuTienda(Window owner)
    {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        filler1 = new Box.Filler(new Dimension(0, 5), new Dimension(0, 5), new Dimension(32767, 5));
        jLabel2 = new JLabel();
        filler2 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jSplitPane1 = new JSplitPane();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel3 = new JPanel();
        jScrollPane2 = new JScrollPane();
        jTable2 = new JTable();
        jPanel6 = new JPanel();
        jButton2 = new JButton();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();
        jButton3 = new JButton();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tienda");
        setMinimumSize(new Dimension(615, 380));
        setPreferredSize(new Dimension(615, 380));

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        jLabel2.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Tienda");
        jLabel2.setAlignmentX(0.5F);
        jPanel1.add(jLabel2);
        jPanel1.add(filler2);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(260);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel2.setBorder(BorderFactory.createTitledBorder("Lista de artículos disponibles"));
        jPanel2.setLayout(new BorderLayout());

        jTable1.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Artículo", "Precio", "Añadir"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(1).setMinWidth(90);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setBorder(BorderFactory.createTitledBorder("Su carrito"));
        jPanel3.setLayout(new BorderLayout());

        jTable2.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Artículo", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0)
        {
            jTable2.getColumnModel().getColumn(1).setMinWidth(90);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        jPanel3.add(jScrollPane2, BorderLayout.CENTER);

        jButton2.setText("Detalles del carrito");
        jPanel6.add(jButton2);

        jPanel3.add(jPanel6, BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel3);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        jPanel4.setLayout(new BorderLayout());

        jPanel5.setLayout(new FlowLayout(FlowLayout.RIGHT));

        jButton3.setText("Comprar ahora");
        jPanel5.add(jButton3);

        jButton1.setText("Salir");
        jPanel5.add(jButton1);

        jPanel4.add(jPanel5, BorderLayout.SOUTH);

        getContentPane().add(jPanel4, BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSplitPane jSplitPane1;
    private JTable jTable1;
    private JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
