package com.vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HikingCarrot7
 */
public class MenuTienda extends JDialog
{

    public MenuTienda(Window owner)
    {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        filler1 = new Box.Filler(new Dimension(0, 5), new Dimension(0, 5), new Dimension(32767, 5));
        lblNombreTienda = new JLabel();
        filler2 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jSplitPane1 = new JSplitPane();
        panelListaArticulos = new JPanel();
        jScrollPane1 = new JScrollPane();
        tablaArticulos = new JTable();
        panelTablaCarrito = new JPanel();
        jScrollPane2 = new JScrollPane();
        tablaCarrito = new JTable();
        jPanel6 = new JPanel();
        btnDetallesCarrito = new JButton();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();
        btnComprarAhora = new JButton();
        btnSalir = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tienda");
        setMinimumSize(new Dimension(615, 380));
        setPreferredSize(new Dimension(615, 380));

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        lblNombreTienda.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        lblNombreTienda.setText("Tienda");
        lblNombreTienda.setAlignmentX(0.5F);
        jPanel1.add(lblNombreTienda);
        jPanel1.add(filler2);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        panelListaArticulos.setBorder(BorderFactory.createTitledBorder("Lista de artículos disponibles"));
        panelListaArticulos.setLayout(new BorderLayout());

        tablaArticulos.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Artículo", "Precio", ""
            }
        ));
        jScrollPane1.setViewportView(tablaArticulos);
        if (tablaArticulos.getColumnModel().getColumnCount() > 0)
        {
            tablaArticulos.getColumnModel().getColumn(1).setMinWidth(90);
            tablaArticulos.getColumnModel().getColumn(1).setPreferredWidth(90);
            tablaArticulos.getColumnModel().getColumn(1).setMaxWidth(90);
            tablaArticulos.getColumnModel().getColumn(2).setMinWidth(40);
            tablaArticulos.getColumnModel().getColumn(2).setPreferredWidth(40);
            tablaArticulos.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        panelListaArticulos.add(jScrollPane1, BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(panelListaArticulos);

        panelTablaCarrito.setBorder(BorderFactory.createTitledBorder("Su carrito"));
        panelTablaCarrito.setLayout(new BorderLayout());

        tablaCarrito.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Artículo", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tablaCarrito);
        if (tablaCarrito.getColumnModel().getColumnCount() > 0)
        {
            tablaCarrito.getColumnModel().getColumn(1).setMinWidth(90);
            tablaCarrito.getColumnModel().getColumn(1).setPreferredWidth(90);
            tablaCarrito.getColumnModel().getColumn(1).setMaxWidth(90);
        }

        panelTablaCarrito.add(jScrollPane2, BorderLayout.CENTER);

        btnDetallesCarrito.setText("Detalles del carrito");
        jPanel6.add(btnDetallesCarrito);

        panelTablaCarrito.add(jPanel6, BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(panelTablaCarrito);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        jPanel4.setLayout(new BorderLayout());

        jPanel5.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnComprarAhora.setText("Comprar ahora");
        jPanel5.add(btnComprarAhora);

        btnSalir.setText("Salir");
        jPanel5.add(btnSalir);

        jPanel4.add(jPanel5, BorderLayout.SOUTH);

        getContentPane().add(jPanel4, BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnComprarAhora()
    {
        return btnComprarAhora;
    }

    public JButton getBtnDetallesCarrito()
    {
        return btnDetallesCarrito;
    }

    public JButton getBtnSalir()
    {
        return btnSalir;
    }

    public JLabel getLblNombreTienda()
    {
        return lblNombreTienda;
    }

    public JPanel getPanelListaArticulos()
    {
        return panelListaArticulos;
    }

    public JPanel getPanelTablaCarrito()
    {
        return panelTablaCarrito;
    }

    public JTable getTablaArticulos()
    {
        return tablaArticulos;
    }

    public JTable getTablaCarrito()
    {
        return tablaCarrito;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnComprarAhora;
    private JButton btnDetallesCarrito;
    private JButton btnSalir;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JPanel jPanel1;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSplitPane jSplitPane1;
    private JLabel lblNombreTienda;
    private JPanel panelListaArticulos;
    private JPanel panelTablaCarrito;
    private JTable tablaArticulos;
    private JTable tablaCarrito;
    // End of variables declaration//GEN-END:variables
}
