package com.vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author HikingCarrot7
 */
public class VistaDetallesPaquete extends JDialog
{

    public VistaDetallesPaquete(Window owner)
    {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        GridBagConstraints gridBagConstraints;

        jSplitPane1 = new JSplitPane();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        treePaquete = new JTree();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        txtDescripcion = new JTextField();
        jLabel3 = new JLabel();
        txtCategoria = new JTextField();
        jLabel4 = new JLabel();
        txtPrecio = new JTextField();
        jLabel5 = new JLabel();
        txtIdentificador = new JTextField();
        jPanel4 = new JPanel();
        jLabel1 = new JLabel();
        txtDescuento = new JTextField();
        jPanel1 = new JPanel();
        filler1 = new Box.Filler(new Dimension(0, 5), new Dimension(0, 5), new Dimension(32767, 5));
        lblPaquete = new JLabel();
        filler2 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jPanel5 = new JPanel();
        btnAceptar = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalles de un paquete");
        setMinimumSize(new Dimension(500, 370));
        setPreferredSize(new Dimension(500, 370));

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel2.setBorder(BorderFactory.createTitledBorder("Contenido del paquete"));
        jPanel2.setLayout(new BorderLayout());

        jScrollPane1.setViewportView(treePaquete);

        jPanel2.add(jScrollPane1, BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setBorder(BorderFactory.createTitledBorder("Detalles del artículo"));
        jPanel3.setLayout(new GridBagLayout());

        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText("Descripción:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        txtDescripcion.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(txtDescripcion, gridBagConstraints);

        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText("Categoría:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtCategoria.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(txtCategoria, gridBagConstraints);

        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(jLabel4, gridBagConstraints);

        txtPrecio.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(txtPrecio, gridBagConstraints);

        jLabel5.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel5.setText("Identificador:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(jLabel5, gridBagConstraints);

        txtIdentificador.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(txtIdentificador, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jPanel4, gridBagConstraints);

        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel1.setText("Descuento:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(jLabel1, gridBagConstraints);

        txtDescuento.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        jPanel3.add(txtDescuento, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel3);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(filler1);

        lblPaquete.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        lblPaquete.setHorizontalAlignment(SwingConstants.CENTER);
        lblPaquete.setText("Detalles del paquete...");
        lblPaquete.setAlignmentX(0.5F);
        jPanel1.add(lblPaquete);
        jPanel1.add(filler2);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        jPanel5.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnAceptar.setText("Aceptar");
        jPanel5.add(btnAceptar);

        getContentPane().add(jPanel5, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAceptar()
    {
        return btnAceptar;
    }

    public JLabel getLblPaquete()
    {
        return lblPaquete;
    }

    public JTree getTreePaquete()
    {
        return treePaquete;
    }

    public JTextField getTxtCategoria()
    {
        return txtCategoria;
    }

    public JTextField getTxtDescripcion()
    {
        return txtDescripcion;
    }

    public JTextField getTxtIdentificador()
    {
        return txtIdentificador;
    }

    public JTextField getTxtPrecio()
    {
        return txtPrecio;
    }

    public JTextField getTxtDescuento()
    {
        return txtDescuento;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAceptar;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JScrollPane jScrollPane1;
    private JSplitPane jSplitPane1;
    private JLabel lblPaquete;
    private JTree treePaquete;
    private JTextField txtCategoria;
    private JTextField txtDescripcion;
    private JTextField txtDescuento;
    private JTextField txtIdentificador;
    private JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
